# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImuCY36FurmaCIlhx9gulsr3pne0cvMv
"""

import requests

def get_data_from_api(endpoint):
    url = f"https://api.frankfurter.app/{endpoint}"
    response = requests.get(url)
    return response.json()

link = "https://api.frankfurter.app"
P_link = requests.get(link)
print(P_link)

currencies = get_data_from_api("currencies")
print(currencies)