# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from api import get_data_from_api

def get_currencies():
    return get_data_from_api("currencies")

def get_latest_rate(from_currency, to_currency):
    endpoint = f"latest?from={from_currency}&to={to_currency}"
    return get_data_from_api(endpoint)

def get_historical_rate(from_currency, to_currency, date):
    endpoint = f"{date}?from={from_currency}&to={to_currency}"
    return get_data_from_api(endpoint)